# 布局与边界参数
layout_domain: [0.1, 0.1]    # 布局域尺寸 [m]（扩大以避免元件重叠）
mesh_size: [256, 256]        # 网格尺寸（y方向256格，x方向256格 → 节点257x257）
num_samples: 3000          # 总样本数
save_root: "./heat_dataset"  # 数据保存根目录

boundary_temperature: 298.0  # 边界温度 [K]
boundary_conditions:         # 边界线段（示例：底部和顶部）
  - [[0.03, 0.0], [0.05, 0.0]]
  - [[0.0, 0.01], [0.0, 0.02]]

# 元件参数（匹配表格范围：尺寸0.006~0.024m，功率4000~10000W）
component:
  shapes: ["rect", "circle", "capsule"]  # 可选形状
  shape_probs: [0.4, 0.3, 0.3]           # 形状概率
  distribution: "uniform"                # 分布类型-均匀分布

  # 矩形尺寸范围 [min, max]
  rect:
    width: [0.006, 0.024]   # 长度 [m]
    height: [0.006, 0.024]  # 宽度 [m]

  # 圆形半径范围 [min, max]
  circle:
    radius: [0.003, 0.012]  # 半径 [m]（=宽度/2）

  # 胶囊形尺寸范围 [min, max]
  capsule:
    length: [0.012, 0.048]  # 总长度 [m]
    width: [0.006, 0.012]   # 宽度 [m]

  # 功率范围 [min, max]
  power:
    min: 4000      # 最小值
    max: 10000    # 最大值
    step: 1000     # 步长（例如2000表示4000,6000,...,20000）